import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { PageHeader } from "../components/shared/page-header";
import { DashboardLayout } from "../layouts/dashboard-layout";

const formats = ["OpenAPI JSON", "OpenAPI YAML", "Swagger", "GraphQL SDL", "GraphQL Introspection"];

export function NewScanPage() {
  return <DashboardLayout><PageHeader title="Create a new scan" description="Provide an API specification or target URL. This is a mock configuration screen." action={<Button>Run Scan</Button>} /><div className="grid gap-4 xl:grid-cols-[1.35fr_0.9fr]"><div className="space-y-4"><Card className="p-5 sm:p-6"><p className="font-semibold">Upload API Specification</p><p className="mt-1 text-sm text-muted">Supported: {formats.join(" · ")}</p><label className="mt-5 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-emerald-400/40 bg-emerald-400/[0.03] p-6 text-center transition-colors hover:bg-emerald-400/[0.08]"><span className="text-sm font-medium text-accent">Drop a specification file here</span><span className="mt-2 text-xs text-muted">or click to browse from your device</span><input className="sr-only" type="file" accept=".json,.yaml,.yml,.graphql,.gql" /></label></Card><Card className="p-5 sm:p-6"><p className="font-semibold">Paste API URL</p><Input className="mt-4" placeholder="https://api.example.com/openapi.json" /></Card><Card className="p-5 sm:p-6"><p className="font-semibold">Paste API specification text</p><textarea className="mt-4 min-h-40 w-full rounded-xl border border-line bg-slate-900/70 p-3 text-sm outline-none placeholder:text-slate-500 focus:border-emerald-400/60" placeholder="Paste OpenAPI, Swagger, or GraphQL schema text..." /></Card></div><Card className="h-fit p-5 sm:p-6"><p className="font-semibold">Scan Configuration</p><p className="mt-1 text-sm text-muted">Mock options; no request will be sent.</p><div className="mt-5 space-y-5"><label className="block text-sm text-slate-300">Scan depth<select className="mt-2 h-10 w-full rounded-lg border border-line bg-slate-900 px-3 text-sm"><option>Standard</option><option>Quick</option><option>Comprehensive</option></select></label><div><p className="text-sm text-slate-300">Authentication options</p><div className="mt-2 rounded-xl border border-line bg-slate-900/50 p-3 text-sm text-muted">No authentication configured</div></div><label className="flex items-center justify-between gap-3 text-sm text-slate-300"><span>Include cloud recommendations</span><input defaultChecked type="checkbox" className="h-4 w-4 accent-emerald-400" /></label><Button className="w-full">Run Scan</Button></div></Card></div></DashboardLayout>;
}
