import { Card } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { PageHeader } from "../components/shared/page-header";
import { DashboardLayout } from "../layouts/dashboard-layout";

function SettingCard({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <Card className="p-5 sm:p-6"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-muted">{description}</p><div className="mt-5">{children}</div></Card>; }

export function SettingsPage() {
  return <DashboardLayout><PageHeader title="Settings" description="Configure local dashboard preferences and placeholder integrations." /><div className="grid gap-4 xl:grid-cols-2"><SettingCard title="Appearance" description="Dashboard visual preferences."><label className="flex items-center justify-between text-sm text-slate-300"><span>Dark appearance</span><input defaultChecked type="checkbox" className="h-4 w-4 accent-emerald-400" /></label></SettingCard><SettingCard title="Notifications" description="Mock alert preferences."><div className="space-y-3 text-sm text-slate-300"><label className="flex justify-between"><span>Critical findings</span><input defaultChecked type="checkbox" className="accent-emerald-400" /></label><label className="flex justify-between"><span>Scan completion</span><input defaultChecked type="checkbox" className="accent-emerald-400" /></label></div></SettingCard><SettingCard title="Database Connection" description="Placeholder; no connection is made."><Input placeholder="sqlite:///./aegisapi.db" /><p className="mt-2 text-xs text-muted">Configuration will be connected in a later phase.</p></SettingCard><SettingCard title="Cloud Provider Preferences" description="Select preferred advisory providers."><div className="flex flex-wrap gap-4 text-sm text-slate-300">{["AWS", "Azure", "GCP"].map(provider => <label key={provider} className="flex items-center gap-2"><input defaultChecked type="checkbox" className="accent-emerald-400" />{provider}</label>)}</div></SettingCard><SettingCard title="API Keys" description="Placeholder credential management."><Input type="password" value="••••••••••••••••" readOnly /><p className="mt-2 text-xs text-muted">Keys are not stored or sent from this mock frontend.</p></SettingCard></div></DashboardLayout>;
}
import type { ReactNode } from "react";
